### ISSUE TITLE
Contrastive loss

### ISSUE THREAD

**Issue by venkatasg** [venkatasg/Lil-Bevo#9]
Need to setup BevoEncoder for MLM, or use off the shelf encoder.

[CLS] good  . [CLS] prompt > [CLS]. bad  [CLS].prompt

Per token basis like Electra?

What corruptions are allowed? As long we use the tokens from the data is anything fine?

**Comment by venkatasg** [comment]
Didn't really work?

**Comment by juand-r** [comment]
We didn't really fully explore the space...
